MyDemoClientAddress/MyDemoClientAddress/Models/Contact.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace MyDemoClientAddress.Models
{
    public class Contact
    {
        public int ContactId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string CountryId { get; set; }
        public string StateId { get; set; }
        public string Postcode { get; set; }
        public string FullAddress { get; set; }
        public int GridTotalPages { get; set; }
    }
}

MyDemoClientAddress/MyDemoClientAddress/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyDemoClientAddress.Models;
using MyDemoClientAddress.Services;

namespace MyDemoClientAddress.Controllers
{
    public class ContactController : Controller
    {
        private readonly ContactService _contactService;

        public ContactController()
        {
            _contactService = new ContactService();
        }

        // GET: Contact
        [HttpGet]
        public ActionResult Index(int pageNumber = 1)
        {
            var contacts = _contactService.Select(pageNumber, 20);
            return View(contacts);
        }

        [HttpPost]
        public JsonResult Select(int pageNumber, int pageSize)
        {
            return Json(_contactService.Select(pageNumber, pageSize));
        }

        [HttpPost]
        public JsonResult Insert(Contact contact, int pageNumber, int pageSize)
        {
            var errMsg = _contactService.ValidContact(contact);
            if (errMsg.Length > 0)
                return Json(new { error = errMsg });
            
            _contactService.Insert(contact);
            return Json(_contactService.Select(pageNumber));
        }

        [HttpPost]
        public JsonResult Update(Contact contact, int pageNumber, int pageSize)
        {
            var errMsg = _contactService.ValidContact(contact);
            if (errMsg.Length > 0)
                return Json(new { error = errMsg });

            _contactService.Update(contact);
            return Json(_contactService.Select(pageNumber));
        }

        [HttpPost]
        public ActionResult Delete(int id, int pageNumber, int pageSize)
        {
            _contactService.Delete(id);

            return Json(_contactService.Select(pageNumber));

        }
    }
}

MyDemoClientAddress/MyDemoClientAddress/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "MyContact";
}
@model IEnumerable<MyDemoClientAddress.Models.Contact>
<style>
    .tablemy {
        max-width: none;
        table-layout: fixed;
        word-wrap: break-word;
    }

    .fontSmall {
        font-size: small;
    }

    .btnmy {
        font-size: 16px;
        font-weight: 300;
        text-transform: uppercase;
        letter-spacing: 1.4px;
        /*margin-bottom: 20px;*/
    }

    .labelmy {
        margin-bottom: 5px;
        font-weight: 600;
    }
</style>
<div class="container">
    <div class="row mt-5 justify-content-center">
        <div class="col-md-8 order-md-1">
            <h4 class="mb-3">Contact Add / Edit</h4>
            <form class="needs-validation" novalidate="" action="post">
                <input id="contactId" type="hidden" />
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="firstName" class="labelmy">Firstname</label>
                        <input class="form-control" id="firstName" required="" type="text" placeholder="" value="">
                        <div class="invalid-feedback">
                            Valid first name is required.
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="lastName" class="labelmy">Lastname</label>
                        <input class="form-control" id="lastName" required="" type="text" placeholder="" value="">
                        <div class="invalid-feedback">
                            Valid last name is required.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="middleName" class="labelmy">Middlename <span class="font-weight-normal text-muted">(Optional)</span></label>
                        <input class="form-control" id="middleName" type="text" placeholder="" value="">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="phone" class="labelmy">Phone</label>
                        <input class="form-control" id="phone" required="" type="text">
                        <div class="invalid-feedback">
                            Valid mobile or phone number is required.
                        </div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="email" class="labelmy">Email <span class="font-weight-normal text-muted">(Optional)</span></label>
                    <input class="form-control" id="email" type="email">
                </div>
                <div class="mb-3">
                    <label for="address" class="labelmy">Address</label>
                    <input class="form-control" id="address" required="" type="text">
                    <div class="invalid-feedback">
                        Valid address is required.
                    </div>
                </div>
                <div class="mb-3">
                    <label for="address2" class="labelmy">Address 2 <span class="font-weight-normal text-muted">(Optional)</span></label>
                    <input class="form-control" id="address2" type="text" placeholder="">
                </div>
                <div class="row">
                    <div class="col-md-5 mb-3">
                        <label for="country" class="labelmy">Country</label>
                        <select class="custom-select d-block w-100" id="country" required="">
                            <option value="">Select...</option>
                            <option value="AUS">Australia</option>
                        </select>
                        <div class="invalid-feedback">
                            Valid country is required.
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="state" class="labelmy">State</label>
                        <select class="custom-select d-block w-100" id="state" required="">
                            <option value="">Select...</option>
                            <option value="ACT">ACT</option>
                            <option value="NT">NT</option>
                            <option value="NSW">NSW</option>
                            <option value="QLD">QLD</option>
                            <option value="TAS">TAS</option>
                            <option value="VIC">VIC</option>
                            <option value="WA">WA</option>
                        </select>
                        <div class="invalid-feedback">
                            Valid state is required.
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="pcode" class="labelmy">Postcode</label>
                        <input class="form-control" id="pcode" required="" type="text" placeholder="">
                        <div class="invalid-feedback">
                            Valid post code is required.
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 mb-4">
                        <button class="btn btn-primary btn-block btnmy" id="btnSave" type="button">Save</button>
                    </div>
                    <div class="col-md-4 mb-4">
                        <button class="btn btn-block btnmy" id="btnClear" type="button">Clear</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-8 offset-2 order-md-1 alert alert-danger d-none" id="divError" role="alert">
            <h4 class="alert-heading">Please fix the following errors and re-submit form.</h4>
            <p></p>
        </div>
    </div>
</div>
@*
    d-none d-md-block will hide this container when the Viewport is small or extra small
*@
<div class="container-fluid">
    <hr class="mb-4">
    <div class="form-inline">
        <input type="hidden" id="pageNo" value="1" />
        @{
            if (Model != null && Model.Count() > 0)
            {
                <input type="hidden" id="totalPages" value="@Model.First().GridTotalPages" />
            }
            else
            {
                <input type="hidden" id="totalPages" value="1" />
            }
        }
    </div>
    <table class="table tablemy fontSmall">
        <thead class="thead-light">
            <tr>
                @*d-none d-md-table-cell - Only show these cells when viewport is medium or greater*@
                <th scope="col" class="d-none d-md-table-cell"></th>
                <th scope="col" class="d-none d-md-table-cell"></th>
                @*py-0 - padding top and bottom 0 (bootstrap) measurement. pr-2 - padding right 2 measurement.*@
                <th class="py-0" colspan="2"><a id="btnFirst" href="#"><span class="fa fa-step-backward pr-2"></span></a><a id="btnPrev" href="#"><span class="fa fa-backward pr-2"></span></a><span class="pr-2 font-weight-normal">Page</span><span id="spanPageNo" class="pr-2"></span><span class="pr-2 font-weight-normal">of</span><span id="spanTotalPages" class="pr-2"></span><a id="btnNext" href="#"><span class="fa fa-forward pr-2"></span></a><a id="btnLast" href="#"><span class="fa fa-step-forward pr-2"></span></a><span><select class="custom-select-sm" id="pageSize"><option value="5">5</option><option value="10">10</option><option value="15">15</option><option value="20" selected="selected">20</option></select></span></th>
                <th scope="col" class="d-none d-md-table-cell"></th>
            </tr>
            <tr>
                <th scope="col">Fullname</th>
                @*d-none d-md-table-cell - Only show these cells when viewport is medium or greater*@
                <th scope="col" class="d-none d-md-table-cell">Phone</th>
                <th scope="col" class="d-none d-md-table-cell">Email</th>
                <th scope="col" class="d-none d-md-table-cell">Address</th>
                <th scope="col" class="text-center">Action</th>
            </tr>
        </thead>
        <tbody id="tbody">
            @foreach (var contact in Model)
            {
            <tr data-contactid="@contact.ContactId.ToString()" data-countryid="@contact.CountryId.ToString()" data-stateid="@contact.StateId.ToString()" data-firstname="@contact.FirstName.ToString()" data-middlename="@contact.MiddleName.ToString()" data-lastname="@contact.LastName.ToString()" data-address="@contact.Address.ToString()" data-address2="@contact.Address2.ToString()" data-postcode="@contact.Postcode.ToString()">
                <td>@contact.FullName</td>
                <td class="d-none d-md-table-cell">@contact.Phone</td>
                <td class="d-none d-md-table-cell">@contact.Email</td>
                <td class="d-none d-md-table-cell">@contact.FullAddress</td>
                <td class="text-center"><a id='edit' href='#' title='Edit' class="pr-3"><i class='fa fa-edit'></i></a><a id='delete' href='#' title='Delete'><span><i class='fa fa-trash'></i></span></a></td>
            </tr>
            }
        </tbody>
    </table>
</div>
@section Scripts
{
    <script type="text/javascript" src="~/Scripts/main.js"></script>
    <script type="text/javascript" src="~/Scripts/contact.js"></script>
}

MyDemoClientAddress/MyDemoClientAddress/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Demo App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Home", "Index", "Contact", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                @*my-2 gives padding for only xs because my-sm-0 sets padding 0 for sm and larger*@
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container-fluid body-content">
            @RenderBody()
            @*<hr />*@
            @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>